/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeemanagementsystem;

import java.awt.Color;
import javax.swing.JOptionPane;

/** 
 *
 * @author Amasha
 */
public class adminFrame extends javax.swing.JFrame {
   
    /**
     * Creates new form adminFrame
     */
    public adminFrame() {
        initComponents();
    }
     
    private void initComponentss() {
    
}
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        designPanel = new javax.swing.JPanel();
        adminNameLabel = new javax.swing.JLabel();
        hrManagerIconLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        adminLayeredPane = new javax.swing.JLayeredPane();
        mainPanel = new javax.swing.JPanel();
        hrManagerFirstNameLabel = new javax.swing.JLabel();
        hrManageremailLabel = new javax.swing.JLabel();
        hrManagerPassworomfirmLabel = new javax.swing.JLabel();
        hrManagerPasswordLabel = new javax.swing.JLabel();
        hrManagerUserNameTextField = new javax.swing.JTextField();
        hrManageremailTextField = new javax.swing.JTextField();
        hrManagerPasswordField = new javax.swing.JPasswordField();
        createHrManLabel = new javax.swing.JLabel();
        hrmanagerConfirmPasswordField = new javax.swing.JPasswordField();
        designationLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        adminbackButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        hrManagerAccountCreateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        designPanel.setBackground(new java.awt.Color(12, 192, 223));

        adminNameLabel.setBackground(new java.awt.Color(12, 192, 223));
        adminNameLabel.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        adminNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminNameLabel.setText("Admin");

        hrManagerIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2(2).png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("----------------------------------------");

        javax.swing.GroupLayout designPanelLayout = new javax.swing.GroupLayout(designPanel);
        designPanel.setLayout(designPanelLayout);
        designPanelLayout.setHorizontalGroup(
            designPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designPanelLayout.createSequentialGroup()
                .addGroup(designPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(designPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(hrManagerIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(designPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(adminNameLabel)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(designPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        designPanelLayout.setVerticalGroup(
            designPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(designPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(hrManagerIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        getContentPane().add(designPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 630));

        adminLayeredPane.setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(248, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));

        hrManagerFirstNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        hrManagerFirstNameLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        hrManagerFirstNameLabel.setText("First Name");

        hrManageremailLabel.setBackground(new java.awt.Color(255, 255, 255));
        hrManageremailLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        hrManageremailLabel.setText("e-mail address");

        hrManagerPassworomfirmLabel.setBackground(new java.awt.Color(255, 255, 255));
        hrManagerPassworomfirmLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        hrManagerPassworomfirmLabel.setText("Confirm Password");

        hrManagerPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        hrManagerPasswordLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        hrManagerPasswordLabel.setText("Password");

        hrManagerUserNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));

        hrManageremailTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));

        hrManagerPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));

        createHrManLabel.setBackground(new java.awt.Color(255, 255, 255));
        createHrManLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        createHrManLabel.setForeground(new java.awt.Color(12, 192, 223));
        createHrManLabel.setText("Create HR Manager/Assistant Account ");

        hrmanagerConfirmPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));

        designationLabel.setBackground(new java.awt.Color(255, 255, 255));
        designationLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        designationLabel.setText("Designation");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HR Manager", "HR Assistant", " " }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));

        adminbackButton.setBackground(new java.awt.Color(255, 0, 0));
        adminbackButton.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        adminbackButton.setForeground(new java.awt.Color(255, 255, 255));
        adminbackButton.setText("X");
        adminbackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        adminbackButton.setPreferredSize(new java.awt.Dimension(26, 26));
        adminbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbackButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(47, 128, 174));

        hrManagerAccountCreateButton.setBackground(new java.awt.Color(47, 128, 174));
        hrManagerAccountCreateButton.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        hrManagerAccountCreateButton.setForeground(new java.awt.Color(255, 255, 255));
        hrManagerAccountCreateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/312.png"))); // NOI18N
        hrManagerAccountCreateButton.setText("Create");
        hrManagerAccountCreateButton.setContentAreaFilled(false);
        hrManagerAccountCreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hrManagerAccountCreateButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hrManagerAccountCreateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hrManagerAccountCreateButtonMouseExited(evt);
            }
        });
        hrManagerAccountCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrManagerAccountCreateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hrManagerAccountCreateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hrManagerAccountCreateButton))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                            .addComponent(createHrManLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminbackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(hrManagerUserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hrManagerFirstNameLabel)
                        .addComponent(hrManageremailLabel)
                        .addComponent(hrManagerPasswordLabel)
                        .addComponent(hrManagerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hrManagerPassworomfirmLabel)
                        .addComponent(hrmanagerConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(designationLabel)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hrManageremailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(adminbackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(createHrManLabel)))
                .addGap(45, 45, 45)
                .addComponent(hrManagerFirstNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hrManagerUserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(hrManagerPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hrManagerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(hrManagerPassworomfirmLabel)
                .addGap(18, 18, 18)
                .addComponent(hrmanagerConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(designationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(hrManageremailLabel)
                .addGap(18, 18, 18)
                .addComponent(hrManageremailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        adminLayeredPane.setLayer(mainPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout adminLayeredPaneLayout = new javax.swing.GroupLayout(adminLayeredPane);
        adminLayeredPane.setLayout(adminLayeredPaneLayout);
        adminLayeredPaneLayout.setHorizontalGroup(
            adminLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminLayeredPaneLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        adminLayeredPaneLayout.setVerticalGroup(
            adminLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(adminLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 790, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hrManagerAccountCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrManagerAccountCreateButtonActionPerformed
       // Retrieve data from GUI components
    String userName = hrManagerUserNameTextField.getText();
    String email = hrManageremailTextField.getText();
    String designation = (String) jComboBox1.getSelectedItem(); // Assuming HR Manager or HR Assistant
    String password = new String(hrManagerPasswordField.getPassword());
    String confirmPassword = new String(hrmanagerConfirmPasswordField.getPassword());

    // Validate passwords
    if (!password.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match. Please try again.");
        return; // Exit the method if passwords don't match
    }

    // Save admin data to file
    fileManagementLogics.saveAdminDataToFile(userName, email, designation, password);

    }//GEN-LAST:event_hrManagerAccountCreateButtonActionPerformed

    private void adminbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbackButtonActionPerformed
        //To back to login page
        new LoginFrameForm().setVisible(true);
    }//GEN-LAST:event_adminbackButtonActionPerformed

    private void hrManagerAccountCreateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hrManagerAccountCreateButtonMouseEntered
         // TO set background colours
        hrManagerAccountCreateButton.setBackground(new Color(204, 204, 204));
        jPanel1.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_hrManagerAccountCreateButtonMouseEntered

    private void hrManagerAccountCreateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hrManagerAccountCreateButtonMouseExited
         // TO set background colours
        hrManagerAccountCreateButton.setBackground(new Color(47, 128, 174));
        jPanel1.setBackground(new Color(47, 128, 174));
    }//GEN-LAST:event_hrManagerAccountCreateButtonMouseExited

    private void hrManagerAccountCreateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hrManagerAccountCreateButtonMouseClicked
         // TO set background colours
        hrManagerAccountCreateButton.setBackground(new Color(0, 0, 51));
        jPanel1.setBackground(new Color(0, 0, 51));
    }//GEN-LAST:event_hrManagerAccountCreateButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane adminLayeredPane;
    private javax.swing.JLabel adminNameLabel;
    private javax.swing.JButton adminbackButton;
    private javax.swing.JLabel createHrManLabel;
    private javax.swing.JPanel designPanel;
    private javax.swing.JLabel designationLabel;
    private javax.swing.JButton hrManagerAccountCreateButton;
    private javax.swing.JLabel hrManagerFirstNameLabel;
    private javax.swing.JLabel hrManagerIconLabel;
    private javax.swing.JPasswordField hrManagerPasswordField;
    private javax.swing.JLabel hrManagerPasswordLabel;
    private javax.swing.JLabel hrManagerPassworomfirmLabel;
    private javax.swing.JTextField hrManagerUserNameTextField;
    private javax.swing.JLabel hrManageremailLabel;
    private javax.swing.JTextField hrManageremailTextField;
    private javax.swing.JPasswordField hrmanagerConfirmPasswordField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
