/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeemanagementsystem;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amasha
 */
public class hrAssistantFrame extends javax.swing.JFrame {

    /**
     * Creates new form hrAssistantFrame
     */
    public hrAssistantFrame() {
        initComponents();
        
         // Set background color for employee table 
        employeeTable.setBackground(Color.WHITE);
        
        // Apply custom table header renderer for employee table
        employeeTable.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                
                // Set font, background color, and foreground color
                c.setFont(new Font("Segoe UI", Font.BOLD, 14));
                c.setBackground(new Color(255, 255, 255));
                c.setForeground(new Color(97, 98, 99));
                
                return c;
            }
        });
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainAssistantPanel = new javax.swing.JPanel();
        hrAssistantLabel = new javax.swing.JLabel();
        hrAssistantIconLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hrAssistantLayeredPane = new javax.swing.JLayeredPane();
        addEmployeePanel = new javax.swing.JPanel();
        employeeManagementAssistantLabel = new javax.swing.JLabel();
        employeeFirstNameAssistantLabel = new javax.swing.JLabel();
        employeeLastAssistantNameLabel = new javax.swing.JLabel();
        employeeEPFAssistantLabel = new javax.swing.JLabel();
        employeedepartmentAssistantLabel = new javax.swing.JLabel();
        employeeDesignationAssistantLabel = new javax.swing.JLabel();
        EmployeeFNameAssistantTextField = new javax.swing.JTextField();
        employeeLNameAssistantTextField = new javax.swing.JTextField();
        employeeEPFAssistantTextField = new javax.swing.JTextField();
        employeeDepNameAssistantTextField = new javax.swing.JTextField();
        employeeDesiNameAssistantTextField = new javax.swing.JTextField();
        hrAssistantBackButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        addNewEmployeeAssistantButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainAssistantPanel.setBackground(new java.awt.Color(12, 192, 223));

        hrAssistantLabel.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        hrAssistantLabel.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        hrAssistantLabel.setForeground(new java.awt.Color(255, 255, 255));
        hrAssistantLabel.setText("HR Assistant");

        hrAssistantIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2(2).png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("----------------------------------------");

        javax.swing.GroupLayout mainAssistantPanelLayout = new javax.swing.GroupLayout(mainAssistantPanel);
        mainAssistantPanel.setLayout(mainAssistantPanelLayout);
        mainAssistantPanelLayout.setHorizontalGroup(
            mainAssistantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainAssistantPanelLayout.createSequentialGroup()
                .addGroup(mainAssistantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainAssistantPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(mainAssistantPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(mainAssistantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hrAssistantIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrAssistantLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainAssistantPanelLayout.setVerticalGroup(
            mainAssistantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainAssistantPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(hrAssistantIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hrAssistantLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        getContentPane().add(mainAssistantPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 630));

        hrAssistantLayeredPane.setBackground(new java.awt.Color(255, 255, 255));

        addEmployeePanel.setBackground(new java.awt.Color(248, 255, 255));
        addEmployeePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));

        employeeManagementAssistantLabel.setBackground(new java.awt.Color(255, 255, 255));
        employeeManagementAssistantLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        employeeManagementAssistantLabel.setForeground(new java.awt.Color(0, 153, 204));
        employeeManagementAssistantLabel.setText("Create Employee Account");

        employeeFirstNameAssistantLabel.setBackground(new java.awt.Color(255, 255, 255));
        employeeFirstNameAssistantLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        employeeFirstNameAssistantLabel.setText("Employee First Name");

        employeeLastAssistantNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        employeeLastAssistantNameLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        employeeLastAssistantNameLabel.setText("Employee Last Name");

        employeeEPFAssistantLabel.setBackground(new java.awt.Color(255, 255, 255));
        employeeEPFAssistantLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        employeeEPFAssistantLabel.setText("Employe EPF No:");

        employeedepartmentAssistantLabel.setBackground(new java.awt.Color(255, 255, 255));
        employeedepartmentAssistantLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        employeedepartmentAssistantLabel.setText("Department Name");

        employeeDesignationAssistantLabel.setBackground(new java.awt.Color(255, 255, 255));
        employeeDesignationAssistantLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        employeeDesignationAssistantLabel.setText("Designation Name");

        EmployeeFNameAssistantTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        EmployeeFNameAssistantTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeFNameAssistantTextFieldActionPerformed(evt);
            }
        });

        employeeLNameAssistantTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        employeeLNameAssistantTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeLNameAssistantTextFieldActionPerformed(evt);
            }
        });

        employeeEPFAssistantTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        employeeEPFAssistantTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeEPFAssistantTextFieldActionPerformed(evt);
            }
        });

        employeeDepNameAssistantTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        employeeDepNameAssistantTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeDepNameAssistantTextFieldActionPerformed(evt);
            }
        });

        employeeDesiNameAssistantTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));

        hrAssistantBackButton.setBackground(new java.awt.Color(255, 0, 51));
        hrAssistantBackButton.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        hrAssistantBackButton.setForeground(new java.awt.Color(255, 255, 255));
        hrAssistantBackButton.setText("X");
        hrAssistantBackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        hrAssistantBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrAssistantBackButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "First Name ", "Last Name", "EPF Number ", "Department ", "Designation"
            }
        ));
        employeeTable.setToolTipText("");
        employeeTable.setGridColor(new java.awt.Color(204, 204, 255));
        employeeTable.setSelectionBackground(new java.awt.Color(255, 153, 153));
        employeeTable.setShowGrid(false);
        employeeTable.setShowHorizontalLines(true);
        employeeTable.setShowVerticalLines(true);
        employeeTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(employeeTable);

        jPanel1.setBackground(new java.awt.Color(47, 128, 174));

        addNewEmployeeAssistantButton.setBackground(new java.awt.Color(47, 128, 174));
        addNewEmployeeAssistantButton.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        addNewEmployeeAssistantButton.setForeground(new java.awt.Color(255, 255, 255));
        addNewEmployeeAssistantButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/312.png"))); // NOI18N
        addNewEmployeeAssistantButton.setText("Add New Employee");
        addNewEmployeeAssistantButton.setContentAreaFilled(false);
        addNewEmployeeAssistantButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewEmployeeAssistantButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addNewEmployeeAssistantButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addNewEmployeeAssistantButtonMouseExited(evt);
            }
        });
        addNewEmployeeAssistantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewEmployeeAssistantButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addNewEmployeeAssistantButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addNewEmployeeAssistantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout addEmployeePanelLayout = new javax.swing.GroupLayout(addEmployeePanel);
        addEmployeePanel.setLayout(addEmployeePanelLayout);
        addEmployeePanelLayout.setHorizontalGroup(
            addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEmployeePanelLayout.createSequentialGroup()
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addEmployeePanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEmployeePanelLayout.createSequentialGroup()
                                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employeeLNameAssistantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(employeeEPFAssistantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(employeeLastAssistantNameLabel)
                                    .addComponent(employeeFirstNameAssistantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmployeeFNameAssistantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(employeeDesiNameAssistantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(employeeDesignationAssistantLabel)
                                    .addComponent(employeeDepNameAssistantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(employeedepartmentAssistantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEmployeePanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
                            .addGroup(addEmployeePanelLayout.createSequentialGroup()
                                .addComponent(employeeEPFAssistantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(addEmployeePanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(employeeManagementAssistantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(287, 287, 287)
                                .addComponent(hrAssistantBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))))
                    .addGroup(addEmployeePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        addEmployeePanelLayout.setVerticalGroup(
            addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeePanelLayout.createSequentialGroup()
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEmployeePanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(employeeManagementAssistantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addEmployeePanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(hrAssistantBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeFirstNameAssistantLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeedepartmentAssistantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeDepNameAssistantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeFNameAssistantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeDesignationAssistantLabel)
                    .addComponent(employeeLastAssistantNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeDesiNameAssistantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeLNameAssistantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeEPFAssistantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(employeeEPFAssistantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(962, 962, 962))
        );

        hrAssistantLayeredPane.setLayer(addEmployeePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout hrAssistantLayeredPaneLayout = new javax.swing.GroupLayout(hrAssistantLayeredPane);
        hrAssistantLayeredPane.setLayout(hrAssistantLayeredPaneLayout);
        hrAssistantLayeredPaneLayout.setHorizontalGroup(
            hrAssistantLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hrAssistantLayeredPaneLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(addEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hrAssistantLayeredPaneLayout.setVerticalGroup(
            hrAssistantLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hrAssistantLayeredPaneLayout.createSequentialGroup()
                .addComponent(addEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(hrAssistantLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 780, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeEPFAssistantTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeEPFAssistantTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeEPFAssistantTextFieldActionPerformed

    private void employeeDepNameAssistantTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDepNameAssistantTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeDepNameAssistantTextFieldActionPerformed

    private void addNewEmployeeAssistantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewEmployeeAssistantButtonActionPerformed
        // Retrieve data from GUI components
        String employeeFName  = EmployeeFNameAssistantTextField.getText();
        String employeeLName = employeeLNameAssistantTextField.getText();
        String employeeEpf = employeeEPFAssistantTextField.getText();
        String employeeDep = employeeDepNameAssistantTextField.getText();
        String employeeDes = employeeDesiNameAssistantTextField.getText();
        
         // Create Employee object
        Employee employee = new Employee();
        employee.setFirstName(employeeFName);
        employee.setLastName(employeeLName);
        employee.setEpf(employeeEpf);
        employee.setDepartment(employeeDep);
        employee.setDesignation(employeeDes);
        
        // Clear the table model to remove existing data
        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
        model.setRowCount(0); // Clear existing rows
        
        //To set table model in fileManagementLogic class
        fileManagementLogics.setEmployeeTableModel((DefaultTableModel) employeeTable.getModel());
    
        // Save department data to file
        fileManagementLogics.saveEmployeeToFile(employee);
      
    }//GEN-LAST:event_addNewEmployeeAssistantButtonActionPerformed

    private void EmployeeFNameAssistantTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeFNameAssistantTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeFNameAssistantTextFieldActionPerformed

    private void employeeLNameAssistantTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeLNameAssistantTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeLNameAssistantTextFieldActionPerformed

    private void hrAssistantBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrAssistantBackButtonActionPerformed
        //To back to login page
        new LoginFrameForm().setVisible(true);
       
    }//GEN-LAST:event_hrAssistantBackButtonActionPerformed

    private void addNewEmployeeAssistantButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewEmployeeAssistantButtonMouseEntered
         // TO set background colours
        addNewEmployeeAssistantButton.setBackground(new Color(204, 204, 204));
        jPanel1.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_addNewEmployeeAssistantButtonMouseEntered

    private void addNewEmployeeAssistantButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewEmployeeAssistantButtonMouseExited
         // TO set background colours
        addNewEmployeeAssistantButton.setBackground(new Color(47, 128, 174));
        jPanel1.setBackground(new Color(47, 128, 174));
    }//GEN-LAST:event_addNewEmployeeAssistantButtonMouseExited

    private void addNewEmployeeAssistantButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewEmployeeAssistantButtonMouseClicked
         // TO set background colours
        addNewEmployeeAssistantButton.setBackground(new Color(0, 0, 51));
        jPanel1.setBackground(new Color(0, 0, 51));
    }//GEN-LAST:event_addNewEmployeeAssistantButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hrAssistantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hrAssistantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hrAssistantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hrAssistantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hrAssistantFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmployeeFNameAssistantTextField;
    private javax.swing.JPanel addEmployeePanel;
    private javax.swing.JButton addNewEmployeeAssistantButton;
    private javax.swing.JTextField employeeDepNameAssistantTextField;
    private javax.swing.JTextField employeeDesiNameAssistantTextField;
    private javax.swing.JLabel employeeDesignationAssistantLabel;
    private javax.swing.JLabel employeeEPFAssistantLabel;
    private javax.swing.JTextField employeeEPFAssistantTextField;
    private javax.swing.JLabel employeeFirstNameAssistantLabel;
    private javax.swing.JTextField employeeLNameAssistantTextField;
    private javax.swing.JLabel employeeLastAssistantNameLabel;
    private javax.swing.JLabel employeeManagementAssistantLabel;
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel employeedepartmentAssistantLabel;
    private javax.swing.JButton hrAssistantBackButton;
    private javax.swing.JLabel hrAssistantIconLabel;
    private javax.swing.JLabel hrAssistantLabel;
    private javax.swing.JLayeredPane hrAssistantLayeredPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainAssistantPanel;
    // End of variables declaration//GEN-END:variables
}
